"""Build `GramVault Index.md` — the landing page for the exported subfolder.

We emit two representations of the same data so the index is useful
whether or not the reader has the Dataview community plugin installed:

  1. A ```dataview``` query block. This requires the Dataview plugin
     (https://github.com/blacksmithgu/obsidian-dataview) to render as a
     live table; without the plugin, Obsidian just shows it as an inert
     fenced code block (harmless, but not a table).
  2. A plain Markdown table built directly from `entries`, so the index is
     still fully useful with zero plugins installed. This table is
     regenerated from scratch on every export — don't hand-edit it.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class IndexEntry:
    item_id: int
    note_filename: str
    author: str
    media_type: str
    date: str
    tags: list[str] = field(default_factory=list)


def escape_table_cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def build_index_markdown(entries: list[IndexEntry], *, subfolder_name: str) -> str:
    """Render the full index note text. `subfolder_name` is the vault-
    relative folder GramVault exported into (used as the Dataview
    `FROM` clause and to build note links)."""
    sorted_entries = sorted(entries, key=lambda e: (e.date or "", e.item_id), reverse=True)

    lines: list[str] = [
        "# GramVault Index",
        "",
        "<!-- Auto-generated by GramVault's Obsidian exporter on every export — do not "
        "hand-edit, your changes will be overwritten. The Dataview block below needs the "
        "Dataview community plugin (https://github.com/blacksmithgu/obsidian-dataview); "
        "if you don't have it installed, use the plain Markdown table further down instead "
        "-- both list the same items and are kept in sync automatically. -->",
        "",
        f"{len(sorted_entries)} item(s) exported.",
        "",
        "## Dataview",
        "",
        "```dataview",
        "TABLE author, type, date, tags",
        f'FROM "{subfolder_name}"',
        "SORT date DESC",
        "```",
        "",
        "## All Items (plain Markdown fallback)",
        "",
        "| Author | Type | Date | Tags | Note |",
        "|---|---|---|---|---|",
    ]

    for entry in sorted_entries:
        tags_cell = ", ".join(entry.tags) if entry.tags else ""
        note_link = f"[[{entry.note_filename}]]"
        lines.append(
            "| "
            + " | ".join(
                escape_table_cell(cell)
                for cell in (entry.author, entry.media_type, entry.date, tags_cell, note_link)
            )
            + " |"
        )

    lines.append("")
    return "\n".join(lines)


__all__ = ["IndexEntry", "build_index_markdown", "escape_table_cell"]
