"""Build `GramVault Dashboard.md` — an at-a-glance view of the exported
library. Same two-representation approach as the index: a ```dataview```
block for plugin users and a plain Markdown fallback that always renders.
"""

from __future__ import annotations

from collections import Counter
from datetime import UTC, datetime, timedelta

from gramvault.export.markdown_builder import MANAGED_END, MANAGED_START
from gramvault.models.schemas import Item

_LOW_CONFIDENCE = 0.6


def _enum_value(value: object) -> str:
    return value.value if hasattr(value, "value") else str(value)


def _recent(items: list[Item], days: int) -> int:
    cutoff = datetime.now(UTC) - timedelta(days=days)
    count = 0
    for item in items:
        stamp = item.imported_at
        if stamp is None:
            continue
        if stamp.tzinfo is None:
            stamp = stamp.replace(tzinfo=UTC)
        if stamp >= cutoff:
            count += 1
    return count


def build_dashboard_markdown(items: list[Item], *, subfolder_name: str) -> str:
    """Render the dashboard note for the `items` just exported."""
    category_counts = Counter(item.category or "— uncategorized —" for item in items)
    uncategorized = sum(1 for item in items if item.category is None)
    low_confidence = sum(
        1
        for item in items
        if item.category is not None
        and _enum_value(item.category_source or "") != "manual"
        and (item.category_confidence or 0) < _LOW_CONFIDENCE
    )
    enrichment_failed = sum(
        1 for item in items if _enum_value(item.enrichment_status) == "failed"
    )

    lines: list[str] = [
        "# GramVault Dashboard",
        "",
        "<!-- Auto-generated by GramVault on every export. Regenerated from "
        "scratch — add your own notes below the end marker. -->",
        "",
        MANAGED_START,
        f"*{len(items)} item(s) in the last export · {_recent(items, 30)} saved in the last 30 days*",
        "",
        "| Metric | Count |",
        "|---|---|",
        f"| Uncategorized | {uncategorized} |",
        f"| Low-confidence auto label | {low_confidence} |",
        f"| Enrichment failed | {enrichment_failed} |",
        "",
        "## By category",
        "",
        "```dataview",
        "TABLE length(rows) AS Count",
        f'FROM "{subfolder_name}"',
        "WHERE category",
        "GROUP BY category",
        "SORT length(rows) DESC",
        "```",
        "",
        "| Category | Count |",
        "|---|---|",
    ]
    for category, count in category_counts.most_common():
        lines.append(f"| {category} | {count} |")
    lines += ["", MANAGED_END, ""]
    return "\n".join(lines)


__all__ = ["build_dashboard_markdown"]
